# Generated by Django 6.0.2 on 2026-02-09 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code_categorie', models.AutoField(primary_key=True, serialize=False, verbose_name='Code Catégorie')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation Catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code_client', models.AutoField(primary_key=True, serialize=False, verbose_name='Code Client')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du Client')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('code_fournisseur', models.AutoField(primary_key=True, serialize=False, verbose_name='Code Fournisseur')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation Fournisseur')),
                ('marge_beneficiaire', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marge Bénéficiaire (%)')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('code_produit', models.AutoField(primary_key=True, serialize=False, verbose_name='Code Produit')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation Produit')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix d'Achat (FC)")),
                ('quantite_stock', models.IntegerField(default=0, verbose_name='Quantité en Stock')),
                ('quantite_alerte', models.IntegerField(default=10, verbose_name='Quantité Alerte')),
                ('date_expiration', models.DateField(verbose_name="Date d'Expiration")),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.categorie', verbose_name='Catégorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('code_vente', models.AutoField(primary_key=True, serialize=False, verbose_name='Code Vente')),
                ('date_vente', models.DateTimeField(auto_now_add=True, verbose_name='Date de Vente')),
                ('type_vente', models.CharField(choices=[('detail', 'Détail'), ('gros', 'Gros')], default='detail', max_length=10, verbose_name='Type de Vente')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant Total (FC)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.client', verbose_name='Client')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité Vendue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix Unitaire (FC)')),
                ('montant_ligne', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant Ligne (FC)')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.produit', verbose_name='Produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacy.vente', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Ligne de Vente',
                'verbose_name_plural': 'Lignes de Vente',
            },
        ),
    ]
