# Generated by Django 6.0.2 on 2026-02-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='jours_alerte_expiration',
            field=models.IntegerField(default=30, verbose_name='Alerte Expiration (jours avant)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite_initiale',
            field=models.IntegerField(default=0, verbose_name='Quantité Initiale'),
        ),
    ]
