# Generated by Django 6.0.2 on 2026-02-09 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_produit_jours_alerte_expiration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='montant_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant Net (FC)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant Remise (FC)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='remise_pourcent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('connexion', 'Connexion')], max_length=20, verbose_name='Action')),
                ('modele', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('detail', models.TextField(blank=True, verbose_name='Détail')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-date_action'],
            },
        ),
    ]
