# Generated by Django 6.0.2 on 2026-02-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_vente_montant_net_vente_montant_remise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='montant_net',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='montant_remise',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='remise_pourcent',
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'Expiration"),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
