# Generated by Django 6.0.2 on 2026-02-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_remove_produit_categorie_remove_vente_montant_net_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_devise', models.CharField(max_length=10, unique=True, verbose_name='Code Devise')),
                ('montant_fc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant en FC')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['code_devise'],
            },
        ),
    ]
