# Generated by Django 4.2.15 on 2026-02-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_taux'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='est_solde',
            field=models.BooleanField(default=True, verbose_name='Soldé'),
        ),
        migrations.AddField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('comptant', 'Comptant'), ('credit', 'À crédit')], default='comptant', max_length=10, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant Payé (FC)'),
        ),
    ]
