# Generated by Django 4.2.15 on 2026-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_vente_est_solde_vente_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_vente_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Prix de Vente (USD)'),
        ),
    ]
