# Generated by Django 4.2.15 on 2026-03-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_produit_prix_vente_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='montant_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Net à Payer (FC)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant Remise (FC)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='remise_pourcent',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Remise (%)'),
        ),
    ]
