# Generated by Django 4.2.15 on 2026-03-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_vente_montant_net_vente_montant_remise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Prix de Vente (USD)'),
        ),
    ]
