# Generated by Django 4.2.15 on 2026-03-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_produit_prix_vente_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_usd',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=16, verbose_name='Prix de Vente (USD)'),
        ),
    ]
