# Generated by Django 6.0.2 on 2026-06-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_alter_produit_prix_vente_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=200, unique=True, verbose_name='Désignation Produit'),
        ),
    ]
