# Generated by Django 6.0.2 on 2026-06-06 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_alter_produit_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('code_inventaire', models.AutoField(primary_key=True, serialize=False, verbose_name='Code Inventaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('nb_produits_comptes', models.IntegerField(default=0, verbose_name='Nb produits comptés')),
                ('total_ecart_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valeur totale écart (FC)')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_theorique', models.IntegerField(verbose_name='Stock théorique')),
                ('stock_physique', models.IntegerField(verbose_name='Stock physique')),
                ('ecart', models.IntegerField(default=0, verbose_name='Écart')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat (FC)")),
                ('valeur_ecart', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valeur écart (FC)')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacy.inventaire', verbose_name='Inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'ordering': ['produit__designation'],
                'unique_together': {('inventaire', 'produit')},
            },
        ),
    ]
