# Generated by Django 6.0.2 on 2026-06-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_inventaire_ligneinventaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventaire',
            name='comptee',
            field=models.BooleanField(default=False, verbose_name='Comptée'),
        ),
    ]
