# Generated by Django 6.0.2 on 2026-06-06 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_ligneinventaire_comptee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='compteurs_autorises',
            field=models.ManyToManyField(blank=True, related_name='inventaires_compteur_autorise', to=settings.AUTH_USER_MODEL, verbose_name='Compteurs autorisés'),
        ),
    ]
