# Generated by Django 6.0.2 on 2026-06-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_inventaire_compteurs_autorises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantite_alerte',
            field=models.IntegerField(default=5, verbose_name='Quantité Alerte'),
        ),
    ]
