# Generated by Django 6.0.2 on 2026-06-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_quantite_alerte_default_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'enregistrement"),
        ),
    ]
