# Generated by Django 6.0.2 on 2026-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('vendeur', 'Vendeur'), ('gestionnaire', 'Gestionnaire'), ('controleur', 'Contrôleur')], default='vendeur', max_length=20, verbose_name='Rôle'),
        ),
    ]
